---
title: "Workstation_Statistics"
author: "Torin White"
date: "July 30, 2020"
output: html_document
---
#Workstation Stats

```{r library_load}
library(tidyverse)
library(googlesheets4)
library(stringr)
#library(rebus) not using anymore
library(RColorBrewer)
library(knitr)
library(lubridate)
library(hms)
```
##pull data from spreadsheet @ https://docs.google.com/spreadsheets/d/1hI-Vc059lvrxGeTBdNxVkXel2Hmyz-Gub5FD0qdJMJU/edit?usp=sharing
###note: spreadsheet is automatically updated with new responses
###only need to run this code chunk if there are new entries to google form
```{r Workstation_data}
# skip if no new entries
data <- read_sheet("https://docs.google.com/spreadsheets/d/1hI-Vc059lvrxGeTBdNxVkXel2Hmyz-Gub5FD0qdJMJU/edit?usp=sharing")
getwd()
setwd("data")
write.csv(data, "Workstation_data.csv")
```


```{r readcsv, echo = FALSE}
# import data from saved csv
getwd()
Workstation_data <- read_csv("data/Workstation_data.csv")
```
```{r data_cleaning, echo=FALSE}
#make Department and Status columns lowercase
Workstation_data$Department <- tolower(Workstation_data$Department)
Workstation_data$Status <- tolower(Workstation_data$Status)
```
```{r trim whitespace, echo=FALSE}

##use str_trim() instead
#trim whitespace
Workstation_data$Department <- trimws(Workstation_data$Department, which = c("both"))
Workstation_data$Status <- trimws(Workstation_data$Status, which = c("both"))
```
## Data Cleaning ##
```{r department cleaning, echo= FALSE}
##Department Normalization

# Normalize anthropology
temp <- Workstation_data$Department %in% c("anth", "anthro")
Workstation_data$Department[temp] <- "anthropology"

#Normalize biology/eemb/mcdb
temp <- Workstation_data$Department %in% c("bio", "biology", "eemb", "mcdb" )
Workstation_data$Department[temp] <- "biology/eemb/mcdb"

#Normalize bren/environmental studies
temp <- Workstation_data$Department %in% c("environmental studies", "bren / environmental studies", "mesm", "environmental science" )
Workstation_data$Department[temp] <- "bren/environmental studies"

#Normalize Communication
temp <- Workstation_data$Department %in% c("comm", "communications")
Workstation_data$Department[temp] <- "communication"

#Normalize computer science
Workstation_data$Department[Workstation_data$Department == "cs"] <- "computer science"

#Normalize earth science
Workstation_data$Department[Workstation_data$Department == "earth sci"] <- "earth sciences"

#Normalize economics
Workstation_data$Department[Workstation_data$Department == "econ"] <- "economics"

#Normalize engineering
temp <- Workstation_data$Department %in% c("mrl", "ece", "electrical engineering")
Workstation_data$Department[temp] <- "engineering"

#Normalize exercise & sport
Workstation_data$Department[Workstation_data$Department == "ess"] <- "exercise & sport"

#Normalize film & media
temp <- Workstation_data$Department %in% c("film and media studies", "famst")
Workstation_data$Department[temp] <- "film & media"

#Normalize geography
temp <- Workstation_data$Department %in% c("geo", "geog")
Workstation_data$Department[temp] <- "geography"

#Normalize global
Workstation_data$Department[Workstation_data$Department == "global studies"] <- "global"

#Normalize physics
Workstation_data$Department[Workstation_data$Department == "phys"] <- "physics"

#Normalize religious
Workstation_data$Department[Workstation_data$Department == "religious"] <- "religious studies"

#Normalize pstat/statistics/actuarial
temp <- Workstation_data$Department %in% c("stats", "pstat", "statistics", "pstat / stats / actuarial", "actuarial science"  )
Workstation_data$Department[temp] <- "pstat/stats/actuarial"

#Normalize tmp
temp <- Workstation_data$Department %in% c("mtm", "tmp")
Workstation_data$Department[temp] <- "technology management"

#Normalize poli sci
temp <- Workstation_data$Department %in% c("polisci", "poli sci")
Workstation_data$Department[temp] <- "political science"

#Normalize psychology
Workstation_data$Department[Workstation_data$Department == "psych"] <- "psychology"

#Normalize n/a
temp <- Workstation_data$Department %in% c("option 35", "other (add to shift log)", "n/a", "*")
Workstation_data$Department[temp] <- "NA"

#check if worked
#which(Workstation_data$Department == "eemb", arr.ind = TRUE)
#unique(Workstation_data$Department)

```

```{r bundle depts, echo=FALSE}
##Bundling depts (not already bundled)
# English, Comp Lit & Writing bundle
temp <- Workstation_data$Department %in% c("english", "comp lit", "writing")
Workstation_data$Department[temp] <- "english/comp lit/writing"

# Chicano, Black, Feminist
temp <- Workstation_data$Department %in% c("chicano studies", "feminist studies", "black studies")
Workstation_data$Department[temp] <- "chican@/black/feminist"


# Philosophy & Religious Studies & History
temp <- Workstation_data$Department %in% c("philosophy", "religious studies", "history")
Workstation_data$Department[temp] <- "philosophy/religion/history"


#Anthropology & Sociology
temp <- Workstation_data$Department %in% c("anthropology", "sociology")
Workstation_data$Department[temp] <- "anthropology/sociology"

#check
#unique(Workstation_data$Department)
```
## Departments Statistics
### All-time Stats
```{r dept_total, echo= FALSE}
#counts visits each dept all time
Dept_count <- Workstation_data %>%
  count(Department) %>%
  arrange(desc(n))

kable(Dept_count, caption = "Total Visits by Department")
          
num_dept <- length(unique(Workstation_data$Department))
# create more colors per: https://www.datanovia.com/en/blog/easy-way-to-expand-color-palettes-in-r/
mycolors <- colorRampPalette(brewer.pal(8, "Set2"))(num_dept)
ggplot(Workstation_data) + 
  stat_count(aes(x = Department, fill = Department)) +
  scale_fill_manual(values = mycolors) + coord_polar() + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

#Top Ten Departments
counted_Dept %>%
  arrange(n) %>%
  slice(21:30) %>%
  ggplot() + 
  aes(x = reorder(Department, n), y = n, fill = Department) +
  scale_fill_manual(values = mycolors) + geom_bar(stat = "identity") + coord_flip()

#Middle ten departments
counted_Dept %>%
  arrange(n) %>%
  slice(11:20) %>%
  ggplot() + 
  aes(x = reorder(Department, n), y = n, fill = Department) +
  scale_fill_manual(values = mycolors) + geom_bar(stat = "identity") + coord_flip() 

#Lowest ten departments
counted_Dept %>%
  arrange(n) %>%
  slice(1:10) %>%
  ggplot() + 
  aes(x = reorder(Department, n), y = n, fill = Department) +
  scale_fill_manual(values = mycolors) + geom_bar(stat = "identity") + coord_flip()


```

Departments by year 
```{r dept_byyear, echo=FALSE}

```